### ISSUE TITLE
files are not found for indexing

### ISSUE THREAD

**Issue by taich001** [owncloud/search_elastic#162]
I have installed elasticsearch and it is up and running. Then I installed owncloud full text search.

when I go to settings / search I can see that 
34 nodes marked as indexed, 34 documents in index using 364702 bytes

but I have 20000 files.
Furthermore none of my search requests are fullfiled.

Does anyone know how to fix this?

**Comment by taich001** [comment]
I found this in owncloud.log

```
{
  "reqId": "2tDtctzhRcnc63zvWIvA",
  "level": 3,
  "time": "2020-01-30T14:45:02+01:00",
  "remoteAddr": "",
  "user": "yac",
  "app": "search_elastic",
  "method": "--",
  "url": "--",
  "message": "Exception: {"Exception":"ElasticaExceptionClientException",
  "Message":"No enabled connection",
  "Code":0,"Trace":"#0 /var/www/owncloud/apps/search_elastic/vendor/ruflin/elastica/lib/Elastica/Connection/ConnectionPool.php(98): 
    ElasticaConnectionStrategySimple->getConnection(Array)n#1 /var/www/owncloud/apps/search_elastic/vendor/ruflin/elastica/lib/Elastica/Client.php(549): 
    ElasticaConnectionConnectionPool->getConnection()n#2 /var/www/owncloud/apps/search_elastic/vendor/ruflin/elastica/lib/Elastica/Client.php(669): 
    ElasticaClient->getConnection()n#3 /var/www/owncloud/apps/search_elastic/vendor/ruflin/elastica/lib/Elastica/Bulk.php(357): 
    ElasticaClient->request('oc-ocxmt2jz4tcs...', 'POST', '{"index":{"_id"...', Array, 'application/x-n...')n#4 /var/www/owncloud/apps/search_elastic/lib/SearchElasticService.php(342): 
    ElasticaBulk->send()n#5 /var/www/owncloud/apps/search_elastic/lib/SearchElasticService.php(267): 
    OCASearch_ElasticSearchElasticService->indexNode('yac', Object(OCFilesNodeFile), true)n#6 /var/www/owncloud/apps/search_elastic/lib/Jobs/UpdateContent.php(104): 
    OCASearch_ElasticSearchElasticService->indexNodes('yac', Array)n#7 /var/www/owncloud/lib/private/BackgroundJob/Job.php(66): 
    OCASearch_ElasticJobsUpdateContent->run(Array)n#8 /var/www/owncloud/lib/private/BackgroundJob/QueuedJob.php(42): 
    OCBackgroundJobJob->execute(Object(OCBackgroundJobJobList), Object(OCLog))n#9 /var/www/owncloud/core/Command/System/Cron.php(125): 
    OCBackgroundJobQueuedJob->execute(Object(OCBackgroundJobJobList), Object(OCLog))n#10 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(255): 
    OCCoreCommandSystemCron->execute(Object(SymfonyComponentConsoleInputArgvInput), Object(SymfonyComponentConsoleOutputConsoleOutput))n#11 /var/www/owncloud/lib/composer/symfony/console/Application.php(982): 
    SymfonyComponentConsoleCommandCommand->run(Object(SymfonyComponentConsoleInputArgvInput), Object(SymfonyComponentConsoleOutputConsoleOutput))n#12 /var/www/owncloud/lib/composer/symfony/console/Application.php(255): 
    SymfonyComponentConsoleApplication->doRunCommand(Object(OCCoreCommandSystemCron), Object(SymfonyComponentConsoleInputArgvInput), Object(SymfonyComponentConsoleOutputConsoleOutput))n#13 /var/www/owncloud/lib/composer/symfony/console/Application.php(148): 
    SymfonyComponentConsoleApplication->doRun(Object(SymfonyComponentConsoleInputArgvInput), Object(SymfonyComponentConsoleOutputConsoleOutput))n#14 /var/www/owncloud/lib/private/Console/Application.php(165): 
    SymfonyComponentConsoleApplication->run(Object(SymfonyComponentConsoleInputArgvInput), Object(SymfonyComponentConsoleOutputConsoleOutput))n#15 /var/www/owncloud/console.php(106): 
    OCConsoleApplication->run()n#16 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')n#17 {main}",
  "File":"/var/www/owncloud/apps/search_elastic/vendor/ruflin/elastica/lib/Elastica/Connection/Strategy/Simple.php",
  "Line":28}"
}

```

**Comment by taich001** [comment]
I habe more information. Search in local files works, but files on external storage (SMB, Dropbox) are not indexed.

**Comment by DennisonWilliams** [comment]
I can confirm that ownCloud 10.3.2 (stable) does not support external SMB even when the'Scan external storages' box is checked

**Comment by maydo** [comment]
Hi, external storage is still not working, will this be fixed ?
